# Generated by Django 4.2.20 on 2025-04-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_faculty1_delete_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty1',
            new_name='Faculty',
        ),
    ]
