# Generated by Django 4.2.20 on 2025-04-09 11:26

import django.core.validators
from django.db import migrations, models
import new_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_rename_faculty1_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(max_length=1, null=True, validators=[new_app.models.gender_validation]),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='age',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(65)]),
        ),
    ]
